version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /app/manage.py migrate --noinput && python /app/manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A nucleus worker -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A nucleus beat -l info
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis