# Generated by Django 3.1.3 on 2020-11-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Subreddit',
        ),
    ]
