# Generated by Django 3.1.3 on 2020-11-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20201129_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='slug',
            field=models.SlugField(default='gaming'),
            preserve_default=False,
        ),
    ]
