# Generated by Django 3.1.3 on 2020-11-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_subreddit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
