# Generated by Django 3.1.3 on 2020-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20201129_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
