# Generated by Django 3.1.3 on 2020-11-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_post_hotness'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
