# Generated by Django 3.1.3 on 2020-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_auto_20201130_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
